apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: green
  template:
    metadata:
      labels:
        app: demo
        version: green
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo
        args:
        - "-text=🟢 GREEN VERSION v2"
        ports:
        - containerPort: 5678
