apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: blue
  template:
    metadata:
      labels:
        app: demo
        version: blue
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo
        args:
        - "-text=🔵 BLUE VERSION v1"
        ports:
        - containerPort: 5678
